### ISSUE TITLE
Merge #20 broke many things. Revert?

### ISSUE THREAD

**Issue by marchdf** [AMReX-Combustion/PeleC#26] opened 2019-02-21 16:49 UTC
@emotheau and @rgrout

Merge #20 into development seems to have broken quite a few things: 

- in `Production` folder, the following cases disappeared VIF, Jet2d, Ebdemo, VT 
- The following tests are failing Sod (crashes with NaNs), FIAB (diffing), all the MMS (not compiling), TG 2D vortex case (diffing)

Seems to be a lot going on in the merge. Is there a point in breaking it into pieces and doing this incrementally?

**Comment by emotheau** [comment] 2019-02-21 17:15
* NSCBC is a change of mathematical formulation to impose BCs, this is normal that solutions are not the same as before.  
* For all the cases removed, this was a decision that we made to clean-up the Exec folder to only keep RegTests, Tutorials and NSCBC test cases. The Production folder should have been removed.
* Sod test case works for me, but I noticed that I left DEBUG printing in there.
* Currently only EB_OblqShock and EB_BackStep are not working, but I will provide a fix soon.

**Comment by jrood-nrel** [comment] 2019-02-21 17:18
@emotheau You can see the tests @marchdf is looking at here https://amrex-combustion.github.io/PeleCRegressionTestResults/ . Several cases do not compile and the `Sod-3` case is producing NaNs now.

**Comment by rgrout** [comment] 2019-02-21 17:19
Let’s back it out until fixed.

For test cases they should be configured by default to run with the old “hard” way of imposing BC, with additional input files to make them run with NSCBC, no?

**Comment by marchdf** [comment] 2019-02-21 17:32
I noticed there was a `Production` repo in our private Pele GitLab. Is that where the `Production` cases that were here should be moved?

**Comment by emotheau** [comment] 2019-02-21 18:16
We decided that there is no longer a "hard" way to impose things in ghost-cells because it is mathematically wrong, so only NSCBC are available to impose inflow/outflows. It is explained in the documentation.
There is no need to revert, I will provide a fix for the Sod-3d ASAP. Also the code is not going to change and future developments have to be done on this version to avoid future conflicts (like the spray branch).

**Comment by drummerdoc** [comment] 2019-02-21 18:39
Maybe language issues might have made Emmanuel's comments sound perhaps harsher than intended. Hopefully I can help a little.

It was me that made the call that NSCBC should be "on" by default, but also to preserve the option to tweak flags to make the boundaries act as before.  It was "known" that this would change the regression results, so I hoped that the older results could be recovered by setting the relaxation parameters appropriately - just to ensure nothing else broke.  Because this change in all cases required a lot of work to update all the cases laying around, we discussed whether it made sense to update the ones nobody cared about....not only for the effort involved, but to decide if the new versions were correct.  Since many of those cases originated from CASTRO and had no relevance to combustion, I advocated dropping as many as possible.  I confirmed with Ray which cases could/should be deleted.  That said, there is no reason any of them can't be added back in if someone thinks the test is important, and if they want then to manage the update of it.  More (maintained) tests are always better.

But anyway, this is why some of the cases from the full set would no longer compile.  It seems like Sod with gamma law probably should work as it's pretty standard for all compressible codes.  However I might argue against supporting gamma law gases here as they are not relevant for combustion except for these kinds of tests (which can/have easily be reconfigured for Fuego gases).  Also, they may be responsible for unnecessary layers in the Eos, and for some unintended bugs in the vectorization of the advection...but again, if people really want that capability, it can be maintained.

We should argue about the primary decision here - that NSCBC should be "on" by default for all cases moving forward.  My view is that anyone running PeleC with subsonic in/out boundaries really should understand the issues about wave reflections there, and that NSCBC should be a standard part of the set up.  That said, NREL is really the PeleC lead and you folks are doing much more work with code.  You can override my call here and decide on a better strategy.  I'll just add that design decisions driven solely by maintaining backward compatibility, when there are only a handful of users to date, and all of them are 'primary developers'...that seems like a recipe for unnecessary trouble down the road.

**Comment by rgrout** [comment] 2019-02-21 18:50
I don’t disagree that we want to be moving towards better boundary conditions, but I do want to be able to turn off capability. I’m less interested in backward compatibility than I am in incremental testing, NSCBC in general is a significant  amount of infrastructure that I’d like to be able to run tests with ‘known’ correct behavior that impose bcs the old way for future debugging.

**Comment by emotheau** [comment] 2019-02-21 21:04
Ok I'm going to put a feature to allow to bypass the NSCBC stuff and to impose "hard" values. For the PMF in RegTest, I'm going to put 2 versions: the old one, and the new one with nscbc, is that ok?

**Comment by rgrout** [comment] 2019-02-21 21:13
Superb, thanks.

**Comment by rgrout** [comment] 2019-02-21 21:14
@marchdf can you take a look at the mms compiling issue and see if it is easy to sort?

**Comment by marchdf** [comment] 2019-02-21 21:16
Yep, I will do that now.

**Comment by emotheau** [comment] 2019-02-21 21:19
I've seen that in Testing/PeleC-tests.ini, the PMF_NSCBC test cases are already set up together with the "old" PMF. However in the regression history website, they don't appear. Is there a specific reason or it is a bug that I can fix in the same time?

**Comment by drummerdoc** [comment] 2019-02-21 21:23
@rgrout Totally fine to have a way to switch off nscbc, but I'd like to have it default to "on" if that's ok.

**Comment by rgrout** [comment] 2019-02-21 21:25
@jrood - can you check it nightly tests are using a different tests file and let @emotheau know how to update it?

**Comment by rgrout** [comment] 2019-02-21 21:26
Just noticed @marchdf said TG case is diffing - that’s periodic, right? So it should be identical...

**Comment by emotheau** [comment] 2019-02-21 21:27
I've seen that, I'm checking it

**Comment by jrood-nrel** [comment] 2019-02-21 21:29
I don't use the `.ini` file in the `PeleC/Testing` directory. I use the one here https://github.com/AMReX-Combustion/PeleRegressionTesting/blob/development/NREL/PeleC-tests-peregrine.ini .

**Comment by emotheau** [comment] 2019-02-21 21:37
Hum I don't understand the HIT issue, I have a perfect Diff between the "old" development branch before the merge, and the GC-NSCBC branch. Does the reference solution used to do the regression test is from another old version?

**Comment by marchdf** [comment] 2019-02-21 21:40
It's not the HIT (looks fine on the tests), it is the TG case. And it is periodic but it is 2D. The 3D TG look ok.

**Comment by marchdf** [comment] 2019-02-21 21:50
@rgrout created a pull request to fix MMS compiling. I will be working with @jrood-nrel to run the full suite again.

**Comment by immanuel-baptist** [comment] 2019-02-21 22:30
It wasn't me, it was the other jrood, I promise!

**Comment by emotheau** [comment] 2019-02-21 22:40
I have solved the issue with TG 2D, the fix will be inside all my changes concerning NSCBC

**Comment by emotheau** [comment] 2019-02-22 01:53
I have fixed may things and enabled backward compatibility with "old" regression test cases. Everything should be ok now, I hope. I have created a pull request for the branch "Update_NSCBC"

**Comment by rgrout** [comment] 2019-02-22 02:02
Cool, i’ll merge it as soon as it passes the Travis checks so that it is in before the nightly regression

**Closed** 2019-03-11 19:15 UTC
