### ISSUE TITLE
Assertion dt>0.0 failed in PMF-SRK

### ISSUE THREAD

**Issue by RSuryaNarayan** [AMReX-Combustion/PeleC#396] opened 2021-12-28 19:07 UTC
Hello, 

I tried to run the PMF-SRK case and after about 18 timesteps I get a message saying 

```
Assertion `dt > 0.0' failed, file "../../../Source/Timestep.H", line 141, Msg: "ERROR: dt needs to be positive." !!!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
I encounter the same issue while running a similar case with LuDME

Any fix that has worked previously? 

Thanks a lot

**Comment by shashankNREL** [comment] 2021-12-28 19:29
Hi, 

Can you show us the screen output from the time step right before it crashed. Most probably some of the transport property went negative leading to negative dt computation from the viscous CFL.

**Comment by RSuryaNarayan** [comment] 2021-12-28 19:43
sure, here's the output for the 17th timestep. This popped in the 18th
```
[STEP 17] Coarse TimeStep time: 2.145438438
[STEP 17] FAB kilobyte spread across MPI nodes: [14102 ... 14102]

STEP = 17 TIME = 3.671175287e-09 DT = 4.160580812e-10

...estimated hydro-limited timestep at level 0: 9.054638155e-10
PeleC::estTimeStep (hydro-limited) at level 0:  estdt = 9.054638155e-10
PeleC::compute_new_dt : limiting dt at level 0
 ... new dt computed: 9.054638155e-10
 ... but limiting to: 4.576638893e-10 = 1.1 * 4.160580812e-10
[Level 0 step 18] ADVANCE with dt = 4.576638893e-10
SDC iteration 1 of 3.
... Computing diffusion terms at t^(n)
... Computing hydro advance
... Computing diffusion terms at t^(n+1,1)
... Computing reactions for dt = 4.576638893e-10
SDC iteration 2 of 3.
... Computing hydro advance
... Computing diffusion terms at t^(n+1,2)
... Computing reactions for dt = 4.576638893e-10
SDC iteration 3 of 3.
... Computing hydro advance
... Computing diffusion terms at t^(n+1,3)
... Computing reactions for dt = 4.576638893e-10
[Level 0 step 18] Advanced 8192 cells

TIME= 4.128839176e-09 MASS        = 1.176436065e-08
TIME= 4.128839176e-09 XMOM        = 2.092939812e-26
TIME= 4.128839176e-09 YMOM        = -2.663809056e-23
TIME= 4.128839176e-09 ZMOM        = 8.599141825e-07
TIME= 4.128839176e-09 RHO*e       = -26.51945379
TIME= 4.128839176e-09 RHO*K       = 7.13306614e-05
TIME= 4.128839176e-09 RHO*E       = -26.51938246
TIME= 4.128839176e-09 FUEL PROD   = 0
TIME= 4.128839176e-09 TEMP        = 0.0003445811213

[STEP 18] Coarse TimeStep time: 2.132114001
[STEP 18] FAB kilobyte spread across MPI nodes: [14102 ... 14102]

STEP = 18 TIME = 4.128839176e-09 DT = 4.576638893e-10

2::Assertion `dt > 0.0' failed, file "../../../Source/Timestep.H", line 141, Msg: "ERROR: dt needs to be positive." !!!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 2 in communicator MPI_COMM_WORLD
with errorcode 6.

NOTE: invoking MPI_ABORT causes Open MPI to kill all MPI processes.
You may or may not see output from other processes, depending on
exactly when Open MPI kills them.
--------------------------------------------------------------------------
```
I used the ```inputs_ex``` file

**Comment by baperry2** [comment] 2021-12-28 19:58
What git hashes are you using for PeleC and PelePhysics? It looks like you're using an older version of the code (`inputs_ex` has been replaced with `example.in` and the newer code spits out some additional diagnostic information).

However, I can reproduce the issue with the up-to-date development branch code, it just happens after 39 steps instead of 18:

```
TIME = 7.07296919e-09 MASS        = 1.176443081e-08
TIME = 7.07296919e-09 XMOM        = -1.978170039e-25
TIME = 7.07296919e-09 YMOM        = 4.101633626e-23
TIME = 7.07296919e-09 ZMOM        = 8.598999528e-07
TIME = 7.07296919e-09 RHO*e       = -26.52055127
TIME = 7.07296919e-09 RHO*K       = 7.160002284e-05
TIME = 7.07296919e-09 RHO*E       = -26.52047967
TIME = 7.07296919e-09 FUEL PROD   = 0

TIME = 7.07296919e-09 density     MIN = 0.011929407      MAX = 0.082791357    
TIME = 7.07296919e-09 x_velocity  MIN = -97.150947       MAX = 102.95676      
TIME = 7.07296919e-09 y_velocity  MIN = -56.960716       MAX = 69.960438      
TIME = 7.07296919e-09 z_velocity  MIN = 21.482575        MAX = 337.48033      
TIME = 7.07296919e-09 eint_e      MIN = -8.3856124e+09   MAX = -1.2631052e+09 
TIME = 7.07296919e-09 Temp        MIN = 300              MAX = 2476.4098      
TIME = 7.07296919e-09 pressure    MIN = 1.0127239e+08    MAX = 1.0381311e+08  
TIME = 7.07296919e-09 massfrac    MIN = -9.7190409e-16   MAX = 0.74762301     
TIME = 7.07296919e-09 sumYminus1  MIN = -4.6851412e-13   MAX = 4.4408921e-16  
TIME = 7.07296919e-09 HO2         MIN = -9.7190409e-16   MAX = 0.001910443    

[STEP 39] Coarse TimeStep time: 1.126813777
[STEP 39] FAB kilobyte spread across MPI nodes: [9994 ... 10054]

STEP = 39 TIME = 7.07296919e-09 DT = 1.809696885e-10

PLOTFILE: file = plt00039
Write plotfile time = 0.86854503  seconds

...estimated hydro-limited timestep at level 0: 3.018213168e-10
PeleC::estTimeStep (hydro-limited) at level 0:  estdt = 3.018213168e-10
20::Assertion `dt > 0.0' failed, file "../../../Source/Timestep.H", line 141, Msg: "ERROR: dt needs to be positive." !!!
--------------------------------------------------------------------------
MPI_ABORT was invoked on rank 20 in communicator MPI_COMM_WORLD
with errorcode 6.

```

I agree with @shashankNREL, a diffusion coefficient must be going negative. I'm going to see if I can figure out why this is happening.

**Comment by RSuryaNarayan** [comment] 2021-12-28 20:02
@baperry2 exactly. I just realized that when I looked up the repo here. The pmfsrk.i seems to be common to the version I have and the newest one. I get the same error at 39th timestep. Here's my githash:
```
PeleC git hash: v0.2.1-38-gb677eae-dirty
AMReX git hash: 21.10-14-gc64e719c0
PelePhysics git hash: v0.1-939-g95f956d5
```

**Comment by RSuryaNarayan** [comment] 2022-01-03 13:49
Some insight on this issue: 
Commenting the line https://github.com/AMReX-Combustion/PelePhysics/blob/6e42111dbd05f22cc6398225a98edc221e2a2a02/Transport/Simple.H#L362 in ```PelePhysics/Transport/Simple.H``` doesn't cause this to happen. 
This suggests that there might be some error in the way Non-ideal Chung corrections are applied along with SRK EOS.

**Comment by baperry2** [comment] 2022-01-03 22:22
I did some tests as well and I see the same. The viscosity is going negative when Chung's model is applied, and this appears to be happening at one particular point, and at that point the state variables (T, rho, Yi) all seem to have reasonable values. Chung's model (https://pubs.acs.org/doi/pdf/10.1021/ie00076a024) is empirical and has a quite complex form, so it's possible we are just getting an "unlucky" set of conditions where the model itself is poorly behaved. Or, given the complexity, it's possible there's an implementation bug that only pops up at these particular conditions.

Digging into it a bit more, the [G2 term](https://github.com/AMReX-Combustion/PelePhysics/blob/6e42111dbd05f22cc6398225a98edc221e2a2a02/Transport/Simple.H#L93) is what appears to be causing issues by going negative.

**Comment by marchdf** [comment] 2022-11-22 16:28
I think this may have gotten fixed about 6 months ago: https://github.com/AMReX-Combustion/PelePhysics/pull/273 

Can someone confirm and then we can close?

**Comment by baperry2** [comment] 2023-09-07 23:34
Closing this because of the temporary fix linked by @marchdf above, and because this issue is superseded by https://github.com/AMReX-Combustion/PelePhysics/issues/415

**Closed as completed by baperry2** 2023-09-07 23:34 UTC
